### ISSUE TITLE
Possible bug in OSOA_hadamard

### ISSUE THREAD

**Issue by bertcarnell** [bertcarnell/SOAs#10]
The examples for OSOA_hadamard say that 9 factors are expected, but 10 are produced

`dim(OSOAs_hadamard(9, optimize=FALSE)$array)  ## 9 8-level factors in 24 runs`

`> dim(OSOAs_hadamard(9, optimize=FALSE)$array)`
`[1] 24 10`

Similarly,

`dim(OSOAs_hadamard(m=35, optimize=FALSE)$array) ## 35 8-level factors in 80 runs`

`> dim(OSOAs_hadamard(m=35, optimize=FALSE)$array)`
`[1] 80 36`

**Comment by ugroempi** [comment]
This was indeed a bug. Fixed with 3e7975d.
