### ISSUE TITLE
Possible missing condition for el = 3 in OSOAs_regular.R

### ISSUE THREAD

**Issue by bertcarnell** [bertcarnell/SOAs#16]
On line 80 of OSOAs_regular.R, we have this line...

` if (m > 2*floor((s^(k-1)-1)/(2*(s-1)))) stop("m is too large in combination with el=3")`

Should we add the condition that `el == 3` in the if statement to match the error message.  I can't see any other conditions earlier in the function that would guarantee `el == 3`.  Maybe I'm missing something implicit.

Suggested fix:

` if (el == 3 & m > 2*floor((s^(k-1)-1)/(2*(s-1)))) stop("m is too large in combination with el=3")`

**Comment by ugroempi** [comment]
Thanks for spotting this. I've moved the code line down to the `if (el==3){}` block.
