### ISSUE TITLE
pkgdown website still mentions system requirements for arrangements package

### ISSUE THREAD

**Issue by ugroempi** [bertcarnell/SOAs#33]
... though this is no longer needed. I don't know how to get rid of that portion.

**Comment by bertcarnell** [comment]
fixed in 6fc25c326ff17f21b8de8116a0771d74b1c10836.  still requires a little more testing

**Comment by bertcarnell** [comment]
Updates pass all checks in 80332c84d2ab7de8ed68495bf9cb16e8b034d5dc
