### ISSUE TITLE
Bug in OSOAs when m is too large and el=2

### ISSUE THREAD

**Issue by bertcarnell** [bertcarnell/SOAs#9]
This method errors

`OSOAarbitrary(DoE.base::L16.4.5)`
`Error in aus[, 1:origm] : subscript out of bounds`

This method works correctly

`OSOAarbitrary(DoE.base::L16.4.5, m = 2)`

I think that the reason the first one errors is that internally, m = 4 and origm = 5.  The `aus` matrix only has m = 4 columns, so when the output of origm = 5 columns is requested, there is an error.

I think additional logic needs to be added.  Can you confirm?

**Comment by ugroempi** [comment]
This function should not be called directly. It is called via `OSOAs`, which calls it with different acceptable `m`, depending on the value of `el`: for `el=2`, five columns are possible, for `el=3` only four columns are possible. `OSOAarbitrary(L16.4.5, el=2)` also works. 
But `OSOAs` with `el=2` and a too large column requested (`OSOAs(L16.4.5, m=6)`) also throws the same unescaped error --> implement meaningful error message for too many columns in `OSOAs` for `el=2`

**Comment by ugroempi** [comment]
fixed it in `OSOAs` but also added meaningful error message to the internal function `OSOAarbitrary`
